### ISSUE TITLE
Name (alias) for garden configuration

### ISSUE THREAD

**Issue by petersutter** [gardener/gardenctl-v2#121]
**What would you like to be added**:
Currently, when targeting a garden without using the patterns feature, you have to specify the garden cluster identity, which could be a lengthy name or even a guid. It should be possible, to specify a name for the garden that can be used as alternative when targeting the garden cluster. E.g. the configuration could look like

```yaml
gardens:
- identity: my-landscape-dev
  name: dev
  kubeconfig: ~/relative/path/to/kubeconfig.yaml
```

You should then be able to run `gardenctl target --garden dev` and of course also `gardenctl target --garden my-landscape-dev`

**Why is this needed**:
Users should be able to name and target the garden to their convenience, especially when the garden cluster identity is meaningless (e.g. a GUID) or rather lengthy.
