### ISSUE TITLE
Report / log last error of Bastion

### ISSUE THREAD

**Issue by petersutter** [gardener/gardenctl-v2#143]
**What would you like to be added**:
In case the lastError is set on the Bastion it should be reported to the user when trying to run the `ssh` command.

**Why is this needed**:
To let users see when there is an error when trying to `ssh`

**Comment by tedteng** [comment]
just saw one of the bastion failure cases today. in case need lastError information for reference. 

```
status:
  lastError:
    description: 'Error reconciling Bastion: Internal Server Error'
    lastUpdateTime: "2022-11-23T13:56:44Z"
  lastOperation:
    description: Reconciling the Bastion
    lastUpdateTime: "2022-11-23T13:56:44Z"
    progress: 1
    state: Processing
    type: Create
  observedGeneration: 1
```
