### ISSUE TITLE
gardenctl should pass `--config` to `gardenlogin` so both use the same config file

### ISSUE THREAD

**Issue by hendrikKahl** [gardener/gardenctl-v2#332]
**What would you like to be added**:

When I specify `--config <path to some specific config file>` to `gardenctl target` and request a kubeconfig for a shoot, the generated file has a `users` section like this:

```
users:
- name: my-cluster
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1
      args:
      - get-client-certificate
      command: kubectl-gardenlogin
      env: null
      installHint: Follow the instructions on https://github.com/gardener/gardenlogin#installation
        to install gardenlogin
      interactiveMode: IfAvailable
      provideClusterInfo: true
```

It would be helpful, if `--config <path to some specific config file>` could be added as an argument to `kubectl-gardenlogin` as well.

**Why is this needed**:

As of now, the behavior is inconsistent and leads to unwanted behavior where `gardenctl` and `gardenlogin` use different configuration files.
